package com.nextflow.api.models.enums;

public enum Categoria {
    VENDA_ALIMENTOS,
    VENDA_BEBIDAS,
    VENDA_ROUPAS,
    VENDA_SERVICOS,
    RECEBIMENTO_ALUGUEL,
    PAGAMENTO_DIVIDAS,
    PROMOCOES_VENDAS,
    RECEBIMENTO_COMISSOES,
    COMPRA_ALIMENTOS,
    COMPRA_BEBIDAS,
    COMPRA_MATERIAIS,
    SALARIOS,
    DESPESAS_TRANSPORTE,
    DESPESAS_ENERGIA,
    DESPESAS_AGUA,
    DESPESAS_MANUTENCAO,
    DESPESAS_PUBLICIDADE,
    IMPOSTOS_TAXAS,
    PAGAMENTO_FORNECEDORES,
    OUTRAS_DESPESAS,
    OUTROS_RECEBIMENTOS
}
